In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [11]:
df = pd.read_csv("./data/WeatherHistory2D.csv")
df.head()

                  Formatted Date  Temperature (C)
0  2006-01-01 00:00:00.000 +0100         0.577778
1  2006-01-01 01:00:00.000 +0100         1.161111
2  2006-01-01 02:00:00.000 +0100         1.666667
3  2006-01-01 03:00:00.000 +0100         1.711111
4  2006-01-01 04:00:00.000 +0100         1.183333

In [24]:
df = pd.read_csv("./data/WeatherHistory2D.csv")
df["Formatted Date"] = pd.to_datetime(df["Formatted Date"],utc = True)
df["Year"] = df["Formatted Date"].dt.year
df["Month"] = df["Formatted Date"].dt.month
df["Day"] = df["Formatted Date"].dt.day
df["Hour"] = df["Formatted Date"].dt.hour
df.drop(columns="Formatted Date",inplace=True)
df

       Temperature (C)  Year  Month  Day  Hour
0             0.577778  2005     12   31    23
1             1.161111  2006      1    1     0
2             1.666667  2006      1    1     1
3             1.711111  2006      1    1     2
4             1.183333  2006      1    1     3
...                ...   ...    ...  ...   ...
96448         0.488889  2016     12   31    18
96449         0.072222  2016     12   31    19
96450        -0.233333  2016     12   31    20
96451        -0.472222  2016     12   31    21
96452        -0.677778  2016     12   31    22

[96453 rows x 5 columns]